baseURL = "http://melhuang.com/"
disablePathToLower = true
languageCode = "en-us"
title = "the misfit manager"
theme = "ghostwriter"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
