baseURL = 'https://melhuang.github.io'
languageCode = 'en-us'
title = 'Misfit Manager'
theme = 'compost'

# required
[build]
_merge = 'deep'

# required
[markup]
_merge = 'deep'

# for better seo
[minify]
_merge = 'deep'
