baseURL = "/"
disablePathToLower = true
languageCode = "en-us"
title = "the misfit manager"
theme = "ghostwriter"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/pages/about"
weight = 2